### ISSUE TITLE
Zero length bam records have invalid bin values

### ISSUE THREAD

**Issue by yipal** [biogo/hts#104]
I encountered a problem with biogo's bam output for records that have a zero length alignment, but a non-zero position and reference.  This case can happen when the data has a read pair where one read is mapped, and the mate is unmapped.  The unmapped mate will have the same position and reference as the mapped mate.  In this case, the unmapped mate will have a zero length alignment.

When I output these records to a bam file using biogo's bam writer, and validate the output bam using "picard ValidateSamFile", I get errors like this:
```
ERROR: Record 105026, Read name FOOBAR, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
```
"sambamba_v0.6.6 index -c" reports 
```
sambamba-index: Bin in read with name 'FOOBAR' is set incorrectly (810 instead of expected 6485)
```

I traced this problem back to a difference between picard and biogo's handling of bin calculation.  When picard (and I assume sambamba) encounters a read with 0 length alignment, it adds 1 to the end position before calling reg2bin(), thus considering the alignment to have length 1.  I'm guessing this is a special case that was not mentioned in the SAM specification.  See https://github.com/samtools/htsjdk/blob/c20e0edd361189c3f2bc3718b018dac2ec90530b/src/main/java/htsjdk/samtools/SAMRecord.java#L1554

Here's a diff I made to record.go that addresses the problem in my use case:
```
@@ -132,10 +132,18 @@ func (r *Record) Bin() int {
                return 4680 // reg2bin(-1, 0)
        }
        end := r.End()
+
+       // If the alignment length is zero (for example, if the read is
+       // unmapped), then increment end by 1 and treat the read as length
+       // 1 for binning purposes.
+       if end == r.Pos {
+               end++
+       }
+
        if !internal.IsValidIndexPos(r.Pos) || !internal.IsValidIndexPos(end) {
                return -1
        }
-       return int(internal.BinFor(r.Pos, r.End()))
+       return int(internal.BinFor(r.Pos, end))
 }
```

**Comment by kortschak** [comment]
>I traced this problem back to a difference between picard and biogo's handling of bin calculation. When picard (and I assume sambamba) encounters a read with 0 length alignment, it adds 1 to the end position before calling reg2bin(), thus considering the alignment to have length 1.

Wow. That's horrific.

htslib does this actually [in the alignment length calculation function](https://github.com/samtools/htslib/blob/44c6a36f2894b45ad6cb491833d27c6a2106410f/sam.c#L347-L353).

I would like to have this specified before I make any change here (I would truly like to mark it WONTFIX). I suppose this comes from the fact that SAM is (unfortunately) 1-based. BAM is not though, which allows us to maintain zero-length features (which is a useful feature for breakpoint annotation), lying about it (in unexpected ways) helps no one.

Please file an issue against hts-specs and ping here when it is resolved.

**Comment by kortschak** [comment]
Note that the spec [currently states](https://github.com/samtools/hts-specs/blob/5448ce9385f48458ca2f18b4b752025465089db1/SAMv1.tex#L842-L845):

>\footnotetext{{\sf BIN} is calculated using the {\sf reg2bin()} function
in Section~\ref{sec:code}. For mapped reads this uses {\sf POS-1}
(i.e.,~0-based left position) and the alignment end point using the
alignment length from the {\sf CIGAR} string.

**Comment by yipal** [comment]
Nice find, I missed that.  Following that text, it says: 

> For unmapped reads (e.g.,~paired end reads where only one part is mapped, see
> Section~\ref{sec:recommended-practice}) treat the alignment as
> being length one. 

So it looks like the spec already tells us what to do in this zero length case.

**Comment by kortschak** [comment]
Thanks, I'd not had coffee yet.

That is extremely unfortunate. It's like that is a study in bad decisions. I will make that change when I get back to a keyboard.

**Comment by yipal** [comment]
Thanks again for your help, Dan!
