### ISSUE TITLE
iso8601

### ISSUE THREAD

**Issue by brentp** [biogo/hts#106]
AFAICT, `2010-10-19T00:00:00.000+00:00` is a valid ios8601 date. but it fails to parse with master.

```Go
package main

import "github.com/biogo/hts/sam"

const hdr = `@HD	VN:1.0	SO:coordinate
@SQ	SN:1	LN:249250621	M5:1b22b98cdeb4a9304cb5d48026a85128	UR:ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz	AS:NCBI37	SP:Human
@RG	ID:ERR184232	LB:5916154	SM:HG01311	PI:311	CN:SC	PL:ILLUMINA	DS:SRP001525
@RG	ID:DKFZ:100630_SN143_0256_A15006043_5	PL:ILLUMINA	CN:DKFZ	PI:353	DT:2010-10-19T00:00:00.000+00:00	LB:WGS:DKFZ:ICGC_BL12	SM:52c198b4-7bda-4f81-8101-a322787a10a6	PU:DKFZ:100630_SN143_0256_A15006043_5	PG:fastqtobam`

func main() {
	s, err := sam.NewHeader([]byte(hdr), nil)
	if err != nil {
		panic(err)
	}
	_ = s
}
```

**Comment by kortschak** [comment]
ISO8601 is horribly lax (there are a huge number of cases that we will never see), and the standard costs money to buy. I guess we will iterate to the level of support that is needed. The commonly used ISO8601 mixes basic and extended forms. This gives us a combinatoric explosion if we fully expand it.

**Comment by brentp** [comment]
see brentp/smoove#189

should: "201123-01-01T010000+0100" be a supported time format?

**Comment by brentp** [comment]
(also, much belated thanks for the previous fix)

**Comment by kortschak** [comment]
They are from the future, they probably already have a fix.

I don't think this is worth fixing; the date is clearly corrupt/faux and I think reasonably rejectable.
