### ISSUE TITLE
csi: malformed dummy bin header

### ISSUE THREAD

**Issue by brentp** [biogo/hts#115]
On csi files created by htslib (with bcftools index or with tabix), I see this error.

I think there must be something wrong with the check: `if bins[i].bin == statsDummyBin` in csi_read.go that causes this (given enough data) to trigger when n != 2. I can't find in the spec or htslib code how you came up with that. Is there any other (currently missing) constraint for this check?

For most files, I do not have this problem, but for 1 large file I do.

This is 1 of 2 issues related to CSI that I've found. Opening the other issue presently.

**Comment by brentp** [comment]
If I add `log.Printf("i: %d, n: %d, bins[i]: %+v", i, n, bins[i])` just before that error is returned, I see:
```
 i: 2462, n: 1, bins[i]: {bin:37450 left:{File:11295 Block:19731} records:0 chunks:[]}
```

**Comment by brentp** [comment]
This blind guess change fixes the problem and doesn't introduce other errors:
```Diff
diff --git a/csi/csi_read.go b/csi/csi_read.go
index 97ab3de..58e6cad 100644
--- a/csi/csi_read.go
+++ b/csi/csi_read.go
@@ -132,7 +132,7 @@ func readBins(r io.Reader, version byte) ([]bin, *index.ReferenceStats, error) {
                if err != nil {
                        return nil, nil, fmt.Errorf("csi: failed to read bin count: %v", err)
                }
-               if bins[i].bin == statsDummyBin {
+               if bins[i].bin == statsDummyBin && bins[i].records != 0 {
                        if n != 2 {
                                return nil, nil, errors.New("csi: malformed dummy bin header")
                        }
```

**Comment by kortschak** [comment]
The origin of this would be explained if https://github.com/samtools/hts-specs/issues/70 ever got addressed, but they are too busy "actually doing science" to write decent specs.

**Comment by kortschak** [comment]
If you can find the code in htslib that handles this I'll look into it (I'm on leave and the last thing I feel like dealing with is htslib/samtools code).

**Comment by brentp** [comment]
In htslib, I can't find any reading of the stats bins. They are defined [here](https://github.com/samtools/htslib/blob/8003166a059eb92f532cc64667160bc497a01b13/hts.c#L1279) in an unexported struct.

the are written as here:

https://github.com/samtools/htslib/blob/8003166a059eb92f532cc64667160bc497a01b13/hts.c#L1470

with META_BIN defined as:
```C
// Finds the special meta bin
//  ((1<<(3 * n_lvls + 3)) - 1) / 7 + 1
#define META_BIN(idx) ((idx)->n_bins + 1)
```

**Comment by brentp** [comment]
I have also asked on samtools-help

**Comment by brentp** [comment]
https://sourceforge.net/p/samtools/mailman/samtools-help/?viewmonth=201712

**Comment by brentp** [comment]
IIUC , this would be the appropriate change:
```Diff
diff --git a/csi/csi_read.go b/csi/csi_read.go
index 97ab3de..6db5a8c 100644
--- a/csi/csi_read.go
+++ b/csi/csi_read.go
@@ -132,7 +132,7 @@ func readBins(r io.Reader, version byte) ([]bin, *index.ReferenceStats, error) {
                if err != nil {
                        return nil, nil, fmt.Errorf("csi: failed to read bin count: %v", err)
                }
-               if bins[i].bin == statsDummyBin {
+               if bins[i].bin == uint32(len(bins))+1 {
                        if n != 2 {
                                return nil, nil, errors.New("csi: malformed dummy bin header")
                        }
```

**Comment by kortschak** [comment]
Thanks for looking into this. I should be able to get to this in the next few days. Please ping me if I have not.

**Comment by kortschak** [comment]
This is not fun. Having no coherent spec makes this way more difficult than it should be. The code above is not correct because it uses the number of bins rather than the maximum possible bin number.
