### ISSUE TITLE
csi: missing chunks from CSI index

### ISSUE THREAD

**Issue by brentp** [biogo/hts#116]
I've updated [vcfanno](https://github.com/brentp/vcfanno) to use CSI when available. I did some exhaustive testing and found that in very rare cases, there are missed annotations.
I'm sure this is due to logic in the `Chunks()` method. I have not been able to make a test-case, but I will make a PR that fixes this shortly.

I think it may be related to the logic change that you did for tabix (internal/index) here https://github.com/biogo/hts/pull/20/files

**Comment by kortschak** [comment]
I'll be happy with this when you can find a test case for it that fails without the change.

**Comment by brentp** [comment]
I'm still looking into making a test-case that's not a large file and a go program. 

For my data, the bug manifests at position 2:48027754
 for a 1-base query at that position, 
tabix gives chunks:  `[{{44294528 64021} {44799318 16953}}]`
csi (-m11) gives chunks: `[{{44294528 64021} {44314395 28227}} {{44462751 52241} {44535834 779}}]`

and after the fix I propose csi gives: `[{{44294528 64021} {44314395 28227}} {{44462751 52241} {44573094 25124}}]`

before merging and before the fix the csi chunks are (preceded by the c index):

```
16 {{44294528 64021} {44314395 28227}}
2572 {{44462751 52241} {44535834 779}}
```

before merging and after the fix the csi chunks are:

```
16 {{44294528 64021} {44314395 28227}}
16 {{44535834 779} {44573094 25124}}
2572 {{44462751 52241} {44535834 779}}
```

**Comment by brentp** [comment]
here is a way to reproduce. it creates random intervals, writes to file, indexes with system call to tabix with -m 12, and then tries to pull them back out. My branch does not fix this. I am also attaching a .bed.gz that has the problem interval (36963207..36963208).
[x.bed.gz](https://github.com/biogo/hts/files/1820443/x.bed.gz)

```Go
package main

import (
	"compress/gzip"
	"fmt"
	"io"
	"log"
	"math/rand"
	"os"
	"os/exec"
	"sort"
	"strings"

	"bufio"
	"strconv"

	"github.com/biogo/hts/bgzf"
	"github.com/biogo/hts/bgzf/index"
	"github.com/biogo/hts/csi"
)

func check(err error) {
	if err != nil {
		panic(err)
	}
}

type pair struct {
	start int
	stop  int
}

const MAX = 50000000

func init() {
	rand.Seed(42)
}

func writeRandomBed(path string, N int) []pair {
	f, err := os.Create(path)
	check(err)
	intervals := make([]pair, 0, N)
	bgz := bgzf.NewWriter(f, 1)

	for i := 0; i < N; i++ {
		start := rand.Intn(MAX)
		intervals = append(intervals, pair{start, start + 1 + rand.Intn(2048)})
		if start > 0 {
			intervals = append(intervals, pair{start - 1, start})
		}
	}
	sort.Slice(intervals, func(i, j int) bool {
		if intervals[i].start == intervals[j].start {
			return intervals[i].stop < intervals[j].stop
		}
		return intervals[i].start < intervals[j].start
	})

	for _, iv := range intervals {
		fmt.Fprintf(bgz, "chr1\t%d\t%d\n", iv.start, iv.stop)
	}

	check(bgz.Close())

	p := exec.Command("tabix", "-m", "12", "-f", "--csi", f.Name())
	p.Stderr = os.Stderr
	p.Stdout = os.Stdout
	check(p.Run())
	return intervals
}

func checkInChunks(bgz *bgzf.Reader, chunks []bgzf.Chunk, interval pair) {

	cr, err := index.NewChunkReader(bgz, chunks)
	defer cr.Close()
	check(err)

	b := bufio.NewReader(cr)

	s, e := strconv.Itoa(interval.start), strconv.Itoa(interval.stop)

	for {

		line, err := b.ReadString('\n')
		if len(line) > 0 {
			toks := strings.Split(strings.TrimSpace(line), "\t")
			if toks[1] == s && toks[2] == e {
				return
			}
		}
		if err == io.EOF {
			break
		}
		check(err)

	}
	log.Fatalf("didnt find %v", interval)

}

func main() {

	N := 2000
	path := "x.bed.gz"

	for k := 0; k < 100000; k++ {
		log.Println(k)
		intervals := writeRandomBed(path, N)

		fi, err := os.Open(path + ".csi")
		check(err)

		g, err := gzip.NewReader(fi)
		check(err)
		csi, err := csi.ReadFrom(g)
		check(err)
		fi.Close()

		f, err := os.Open(path)
		check(err)
		bgz, err := bgzf.NewReader(f, 1)
		check(err)

		for _, interval := range intervals {
			ch := csi.Chunks(0, interval.start, interval.stop)
			checkInChunks(bgz, ch, interval)

		}

	}

}
```

**Comment by brentp** [comment]
I have not been able to find a shift value or test-case that errors when I change `csi/csi.go` to have:
```
diff --git a/csi/csi.go b/csi/csi.go
index 22ee7a4..5044f53 100644
--- a/csi/csi.go
+++ b/csi/csi.go
@@ -215,9 +215,8 @@ func (i *Index) Chunks(rid int, beg, end int) []bgzf.Chunk {
                if c < len(ref.bins) && ref.bins[c].bin == b {
                        left := vOffset(ref.bins[c].left)
                        for _, chunk := range ref.bins[c].chunks {
-                               if vOffset(chunk.End) > left {
+                               if vOffset(chunk.End) >= left {
                                        chunks = append(chunks, chunk)
-                                       break
                                }
                        }
                }
```

**Comment by kortschak** [comment]
That seems to work. Would you check that tabix doesn't also have this problem? (The logic at the same point is slightly different, but similar enough to be a worry).

**Comment by kortschak** [comment]
I'm wondering if maybe the issue here is that htslib is less careful to merge adjacent chunks? Either way we need to handle them.

**Comment by brentp** [comment]
The bug doesn't trigger for `hts/tabix` I used the same code as above except for changing csi to tabix.

Why is csi.MergeChunks never used?

**Comment by kortschak** [comment]
`csi.MergeChunks`, like `bam.MergeChunks` is user-facing API for condensing an index that they are creating.

Do you want to send a PR with the fix you're proposing? There does need to be a test, but the reproducer you have above generates the failure pretty quickly, so that generated data can be used.

**Comment by kortschak** [comment]
This appears to be fixed.
