### ISSUE TITLE
header parsing error with CL.

### ISSUE THREAD

**Issue by brentp** [biogo/hts#123]
reported in brentp/goleft#44

A user has a BAM header with:
```
@PG	ID:bwa	PN:bwa	VN:0.7.12-r1039	CL:/commun/data/packages/bwa/bwa-0.7.12/bwa mem -t 10 -M -H @CO	20180608.isidor.: Mapping de bams pour B Isidor/ CHU-Nantes. Les Bams viennent de  -R @RG\tID:18D0609\tLB:18D0609\tSM:18D0609\tPL:illumina\tCN:Nantes /commun/data/pubdb/broadinstitute.org/bundle/1.5/b37/index-bwa-0.7.12/human_g1k_v37.fasta /mnt/beegfs/lindenb/WORK/2018/20180607.ISIDOR.MEDEXOME/FASTQS/18D0609_S1_R1_001.fastq.gz /mnt/beegfs/lindenb/WORK/2018/20180607.ISIDOR.MEDEXOME/FASTQS/18D0609_S1_R2_001.fastq.gz
```

This causes header-parsing to return an error because of [this check](https://github.com/biogo/hts/blob/master/sam/parse_header.go#L184)

because of the tabs in the CL. I don't see an obvious fix given that quoting doesn't appear to be required.

**Comment by lindenb** [comment]
@brentp can you mask the email from the header please.

**Comment by brentp** [comment]
masked. sorry about that.

**Comment by kortschak** [comment]
How are tabs going into CL?

**Comment by kortschak** [comment]
That's not a valid header. What program produced the BAM?

**Comment by brentp** [comment]
I assume bwa mem which will put whatever you ask it to into the header. Do tabs violate the spec?

**Comment by kortschak** [comment]
Why am I not surprised. The spec says that lines match `/^@[A-Z][A-Z](\t[A-Za-z][A-Za-z0-9]:[ -~]+)+$/` or `/^@CO\t.*/`. `\t` is not in `/[ -~]/`. I think we *are* being too strict on `@CO`, but that's not causing this and I can fix that later today.

**Comment by kortschak** [comment]
To be specific about the invalidity of the line above, `@C)` is on the same line as `@PG`. It must not be.

**Comment by kortschak** [comment]
Can the user do this:

```
bwa mem -t 10 -M -H "@CO\t20180608.isidor.:asdf"
```

or does that expand prior to bwa seeing it. I suppose it does.

This ecosystem is horrific.

**Comment by kortschak** [comment]
The correct fix for this is for bwa mem to take '\t' in the command line and expand it.

**Comment by lindenb** [comment]
@kortschak Hi , just to be clear: the command line itself was generated inside newtflow-io where the `\` must be escaped. I'm away from my lab and I don't remember the way I've escaped this line. May be I've been wrong but tools like gatk-hapcaller read this line without any problem.

I thought it was a simple bug in @brentp 's code. In the end can easily replace/remove  this bad line.
