### ISSUE TITLE
Possible issue with SAM record validation

### ISSUE THREAD

**Issue by bsipos** [biogo/hts#133]
The line below compares the length of the sequence stored in a sam.Record to record.Len(). However, Len() calculates the number of bases consumed on the reference and not on the query.

https://github.com/biogo/hts/blob/aafaa03b4ed961cf75d5f7ace0d70cf9fa921f64/sam/record.go#L99

**Comment by kortschak** [comment]
This is working as intended according to the specification; "TLEN: observed Template LENgth". If you want sequence length you either need to store the sequence or calculate it from the CIGAR.

**Comment by bsipos** [comment]
The sequence is present in my records. However its length (r.Seq.Length) is compared to the number of consumed reference bases (cigarLen).

**Comment by kortschak** [comment]
Ahh, sorry. Yes, you are right. PR momentarily.
