### ISSUE TITLE
Is the 9827_2%2349.bam file still available? 

### ISSUE THREAD

**Issue by ZhongbaoShi** [biogo/hts#138]
Somehow we can't download this file. is it still available? 
ftp://ftp.sra.ebi.ac.uk/vol1/ERA242/ERA242167/bam/9827_2%2349.bam

**Comment by kortschak** [comment]
I don't have it. It was a commonly used benchmark bam for htslib as well. Maybe they have it? Otherwise you'll need to contact the SRA admins at EBI.

**Comment by ZhongbaoShi** [comment]
Ok, we will try other way. Thanks your information.
