### ISSUE TITLE
hts/tabix: add name -> id func to api

### ISSUE THREAD

**Issue by brentp** [biogo/hts#15]
ReferenceStats takes an int but nameMap is not exposed to the user. I guess it might be guaranteed that the index inf the Index.Names() slice is the id to send to ReferenceStats, but it would be nice to have a function like

```Go
func (i *Index) Id(name string) (id int, ok bool) {
    id, ok := i.nameMap[name]
}
```

so that the Id could then be sent to ReferenceStats

**Comment by kortschak** [comment]
I would rather not. It's faster to write a helper that does this.

```
func refStatsFor(name string, idx *tabix.Index) (stats index.ReferenceStats, ok bool) {
    for i, n := range idx.Names() {
        if n == name {
            return idx.ReferenceStats(i), true
        }
    }
    return index.ReferenceStats{}, false
}
```

and not writing the method allows clients to decide whether they want the map or the iteration approach.

**Comment by brentp** [comment]
that works.
