### ISSUE TITLE
fai: attempting to create an index from a file with ultra long lines fails

### ISSUE THREAD

**Issue by bloveless** [biogo/hts#169]
### What are you trying to do?

We receive some fasta assemblies that have very long lines. Occasionally in the MBs for a single line.

Currently that causes the bufio scanner to panic with `bufio.Scanner: token too long`.

I'm curious if there is any interest in trying to resolve this by using some sort of buffered reader instead of the bufio.Scanner?

Right now we just error and tell our users to fix the issue and resubmit but if there is interest I can probably get a PR out for this to try and resolve this issue.

### What did you do?

Attempted to create a fai from a fasta file with ultra long lines

### What did you expect to happen?

Index would be created

### What actually happened?

bufio.Scanner: token too long error

### What version of Go and bíogo/hts are you using?

go version go1.22.4 darwin/arm64

biogo/hts v1.4.5

github.com/biogo/hts v1.4.5 h1:mhVCpZaTYlAhBjMaAATGWBnauioBtmvOb0ApLdU4/+0=
github.com/biogo/hts v1.4.5/go.mod h1:GgiMFa6c4eEkwS3kCBRPv3oPgtRm7L8SXvdE9nICnYc=

### Does this issue reproduce with the current master?

Yes

**Comment by kortschak** [comment]
I can't say that I'm wildly sympathetic to users who have FASTA files with line lengths greater than 64KiB.

If you want to send a PR to enable that behaviour, I will look at it. Note that `bufio.Scanner` makes use of a buffered reader, so I don't see any merit in changing that. What I would suggest is something like
```
// NewIndexFromScanner returns a new Index constructed from the FASTA sequence
// in the provided bufio.Scanner which must wrap the FASTA sequence. This
// constructor is provided for abusers of the FASTA specification with regard to
// line length.
//
// 	sc := bufio.NewScanner(f)
// 	sc.Buffer(make([]byte, waytoolong), waytoolong)
// 	i, err := NewIndexFromScanner(sc)
func NewIndexFromScanner(fasta *bufio.Scanner) (Index, error)
```

**Comment by bloveless** [comment]
Sounds good! Thanks for the response and I'll bring it up and see if there is desire to try and get something in here or if we also aren't wildly sympathetic to those users :)

**Comment by bloveless** [comment]
I brought this up to the team and they share your views on the usefulness of this, so I'm going to close this issue. Thanks though!
