### ISSUE TITLE
Feature request: Random access BAM reading by genomic positions

### ISSUE THREAD

**Issue by ssgross** [biogo/hts#34]
Hi,

I have a use case where I need to fetch all reads overlapping a given genomic interval in an indexed BAM (e.g., all reads on chr3 between position 123 and 456). It doesn't seem like there's an easy way to do this in the current code, unless I am missing something. I can probably contribute some code for this if it would be helpful. Thanks!

**Comment by brentp** [comment]
This is possible. Here: https://github.com/brentp/irelate/blob/master/parsers/bam.go#L185-L227 is an example of the usage.

**Comment by ssgross** [comment]
Got it, thanks. I think it would be nice if the API made this common use case a little easier. Right now it seems like you have to call bam.Chunks() on the index, pass the result to bam.NewIterator, than iterate through until you find the first read that starts inside your interval. It's easy enough for me to make a wrapper that just does this but it feels like it should be part of the API, for example:

bam.NewIterator(reader, index, start, end)

and better yet there could be an IndexedBamReader struct that wraps the reader and the index together, since it's very rare to have an index all by itself. Then you could say:

indexedBam.NewIterator(start, end)

Anyway, just a suggestion. Thanks for your help and for writing this library!

**Comment by kortschak** [comment]
Thanks for the suggestion. I doubt that will be added though; the separation of component makes different use cases so much easier to design and think about than it ever was for me using libbam. You should note that having an Index by itself is how the indexing of a BAM is done, so it's not really that rare.

**Comment by brentp** [comment]
FWIW, I have a supporting library for this here: https://godoc.org/github.com/brentp/bigly/bamat

it's a small bit of code that reduces the boiler-plate for random access.
