### ISSUE TITLE
bam.index.Chunks() to take record

### ISSUE THREAD

**Issue by brentp** [biogo/hts#5]
as with the change for tabix (https://github.com/biogo/hts/commit/d68ff49bde0aed2dc309c9a0011f69bc767d3da7)

the bam.index.Chunks (https://github.com/biogo/hts/blob/d97c9136f128c0c61c5315f7dc30e28776d65609/bam/index.go#L60)
should take a Record interface so it's easy to query a bam with just an interval.

If you agree, I can open a PR

**Comment by kortschak** [comment]
No, in this case there is a tight coupling between BAM and SAM (also in the CSI case), so you are already likely to import hts/sam. The use of the sam.Reference means that it's up to the client whether they want the performance impact of a map look-up.

**Comment by brentp** [comment]
makes sense. closing.
