### ISSUE TITLE
bgzf tests failing on go version go1.8beta1 linux/amd64

### ISSUE THREAD

**Issue by brentp** [biogo/hts#50]
I can also get an error to occur in 1.7.3 on the same test if I add a Flush()
That may be a different error.

```Patch
diff --git a/bgzf/bgzf_test.go b/bgzf/bgzf_test.go
index 683d69e..7543460 100644
--- a/bgzf/bgzf_test.go
+++ b/bgzf/bgzf_test.go
@@ -155,6 +155,7 @@ func TestRoundTrip(t *testing.T) {
        if _, err := w.Write([]byte("payload")); err != nil {
                t.Fatalf("Write: %v", err)
        }
+       fmt.Println(w.Flush())
        if err := w.Close(); err != nil {
                t.Fatalf("Writer.Close: %v", err)
        }
```

Here is the error for 1.8beta:

$ go test
--- FAIL: TestRoundTrip (0.00s)
	bgzf_test.go:186: comment is "", want "comment"
	bgzf_test.go:195: mtime is -62135596800, want 100000000
	bgzf_test.go:198: name is "", want "name"
FAIL
FAIL	github.com/biogo/hts/bgzf	0.137s
```

**Comment by brentp** [comment]
The error is gone after changing:
https://github.com/biogo/hts/blob/bd8d23e533d1b32fd6cdcc7b7d9b156c0312cfa5/bgzf/reader.go#L600
to match the if statement above it so that it reads: `bg.Header.Extra = h.Extra`

**Comment by brentp** [comment]
I can also get the error fixed by commenting out the header reset:
https://github.com/biogo/hts/blob/bd8d23e533d1b32fd6cdcc7b7d9b156c0312cfa5/bgzf/reader.go#L255
so maybe there's missing a deep copy of the header.

**Comment by kortschak** [comment]
[This](https://github.com/golang/go/commit/b4e714e59efd21f9140a3e8e2b0182c74bfde437) caused that. I think this [line](https://github.com/golang/go/commit/b4e714e59efd21f9140a3e8e2b0182c74bfde437#diff-c6ddb466414bc294f416623ffb37af83R147) is the problem. I think it is a regression on their part.
