### ISSUE TITLE
Possible bug in internal/index Chunks()

### ISSUE THREAD

**Issue by ssgross** [biogo/hts#53]
I have what I believe is a valid indexed BAM file but I am getting "index: invalid interval" errors when trying to read it. I tracked the problem down to line 169 of internal/index.go. I believe I am querying a reference that happens to have no reads aligned to it in the BAM, so ref.Intervals is empty. Therefore no matter what begin position is passed to Chunks(), there will be an "invalid interval" error. It seems to me a better thing to do in this case would be to return an empty slice of chunks with no error. Otherwise, the behavior should at least be documented so the caller knows this condition must be checked for (it's not intuitive).

Thanks for taking a look!

**Comment by kortschak** [comment]
Can you post a reproducer of the code that is failing for you and a minimal input data set? Please ensure that you are checking the error returned by `idx.Chunks`. `internal.Index.Chunks` should not return a nil `[]bgzf.Chunk` without an error, but I suspect that it does in this case.

**Comment by kortschak** [comment]
Sorry, I misread what you are worried about. It is not possible to return a nil `[]bgzf.Chunk` without saying why. If you use a nil `bgzf.Chunk` as a parameter to `bgzf.Reader.SetChunk` it removes the chunk limitation on the reader which `Iterator` behaviour is based on. The invalid interval error is not hard (maybe it should have just used io.EOF, but it's done now), and it just there to inform the caller that the returned `[]bgzf.Chunk` should not be used. `idx.Chunks` returns an error, this is documentation that it may fail and that the error should be checked before the returned `[]bgzf.Chunks` is used.

**Comment by kortschak** [comment]
Are you satisfied with the answer above? If not, please respond, otherwise I'll close this as invalid in the next few days.
