### ISSUE TITLE
bgzf output not compatible with htslib

### ISSUE THREAD

**Issue by brentp** [biogo/hts#57]
if I bgzip a bed file with biogo, it's not usable from tabix. Here's a test that demonstrates the problem:

```Go
func TestHeader(t *testing.T) {
    buf := new(bytes.Buffer)
    gz := NewWriter(buf, 1)
    gz.Comment = "comment"
    gz.Extra = []byte("extra")

    _, err := gz.Write([]byte("payload"))
    if err != nil {
        t.Fatal("error writing bgzf")
    }
    if err := gz.Close(); err != nil {
        t.Fatal("error closing bgzf")
    }

    b := buf.Bytes()[:16]
    expected := []byte(MagicBlock[:16])
    if !bytes.Equal(b, expected) {
        t.Fatalf("bgzf: incorrect header.\n got    %v\n wanted %v", b, expected)
    }
}
```
The output is:
```
--- FAIL: TestHeader (0.00s)
	bgzf_test.go:87: bgzf: incorrect header.
		 got    [31 139 8 20 0 0 0 0 0 0 11 0 66 67 2 0]
		 wanted [31 139 8 4 0 0 0 0 0 255 6 0 66 67 2 0]
FAIL
```

This is the line failing htslib checks: https://github.com/samtools/htslib/blob/6d927dfa3192492f3015b1bc9a0026f585e93acc/bgzf.c#L1494

**Comment by kortschak** [comment]
I'd rather not conform to an expectation that is not specified.

**Comment by kortschak** [comment]
@brentp Note that in the issue above, John invites a PR for the `bgzf_is_bgzf` behaviour change. I am not interested in doing that since I don't use tabix or, if at all possible, htslib and in the past PRs have languished there. You might want to push that forward if you need the behaviour to change.

**Comment by kortschak** [comment]
I think this is not true now. John has merged a change to htslib that fixes this problem if our documentation is read.

**Comment by brentp** [comment]
For bam, this means that we have to send a `bgzf.Writer` with `OS = 0xff`  to `bam.NewWriter` even with samtools 1.4

**Comment by kortschak** [comment]
Why? The check in `bgzf_is_bgzf` does not require that OS be unknown.

I agree that the compress/gzip behaviour is unfortunate (actually that RFC1952's choice of OS unknown value is unfortunate), but this doesn't actually stop things working.
