### ISSUE TITLE
bam: discard all null bytes after name 

### ISSUE THREAD

**Issue by brentp** [biogo/hts#59]
In the theme of keeping up with a moving non-target.
https://github.com/samtools/htslib/commit/5d114ebd8e9b80622769b8e575c5a9359cd51273

I'll make a PR that replaces `discard(1)` with discard while byte == 0.

**Comment by brentp** [comment]
and this: https://github.com/samtools/htslib/commit/6d927dfa3192492f3015b1bc9a0026f585e93acc

**Comment by kortschak** [comment]
I guess so. Note that the PR should also consider being nice to people who caused that change to be made; it should probably write the correct number of zero bytes.

**Comment by kortschak** [comment]
The zero bytes are not written to disk.

**Comment by brentp** [comment]
my bad.
