### ISSUE TITLE
paper.md missing authors and references

### ISSUE THREAD

**Issue by sb10** [biogo/hts#66]
Hi. In reviewing the paper for https://github.com/openjournals/joss-reviews/issues/168, I find that paper.md does not list authors and their affiliations. Could these be added?

There are also no DOI references. There is, for example, a published paper on the SAM spec out there.

**Comment by kortschak** [comment]
Hi @sb10, I am confused about the absence of authors and their affiliation. This is [present at the commit that was master](https://github.com/biogo/hts/blob/8e70c8e377b2b3c8b3aacf8b8180435a70ec6867/paper/paper.md) when I submitted the paper to JOSS. The current master retains that information.

A PR adding the Li 2009 and Tarasov 2015 papers has been merged.

**Comment by sb10** [comment]
Yes, sorry, I mentally skipped over the table. The referenced PR will indeed fix the reference issue. (I'll be able to tick these items off in the review checklist once a new release tag is created with all the necessary changes.)
