### ISSUE TITLE
paper/examples/flagstat/README.md misleading?

### ISSUE THREAD

**Issue by sb10** [biogo/hts#69]
(The following doesn't affect my review of the paper, because paper.md makes no performance claims, and strictly speaking flagstat/README.md doesn't say anything too unreasonable)

flagstat/README.md compares performance of biogo/hts with samtools, demonstrating that biogo becomes faster than samtools as more cores are used. However, it is misleading that you don't compare to samtools using multiple threads.

(Also, in my hands, 8 cores is not enough to make biogo faster than single-threaded samtools; the core scaling I see is very bad - could it be a bug?)

My own timings:

samtools 1.3.1-45-g30bc5e2 (using htslib 1.3.2-204-g255863e)
> real	1m58.898s
user	1m56.319s
sys	0m2.576s

samtools flagstat --input-fmt-option nthreads=8
> real	0m22.954s
user	2m40.638s
sys	0m14.881s

(5x faster for 8x more cores, 0.6 scaling)

biogo 1.0.1 (using go v 1.7.5) GOMAXPROCS=1
> real	7m26.520s
user	7m22.924s
sys	0m4.904s

biogo GOMAXPROCS=8
> real	4m2.774s
user	24m8.423s
sys	0m44.927s

(1.8x faster for 8x more cores, 0.2 scaling)
(half the speed of samtools using 7 more cores)

**Comment by kortschak** [comment]
Thanks, I had been looking for how to use multiple threads with samtools flagstat (the help gives no indication giving just an arcane `[--input-fmt-option OPT=VAL]` which reminds me of George Berkeley's question about the presence of trees in a garden with no people). I will add the comparisons.

Maybe try go1.8rc2? The scheduler may have improved since 1.7. I will repeat the full set of comparisons tomorrow when I am back at my workstation.

**Comment by sb10** [comment]
Using go1.8rc3 I get a similar time with 8 cores:

> real	3m30.125s
user	21m50.410s
sys	0m39.118s

Faster than go1.7, but still much slower than single-threaded samtools.

PS. 
I haven't looked through the API to see all the possibilities, but I notice the use of b.Omit(bam.AllVariableLengthData) in the flagstat example.
When I wrote a minimal tool for using the C samtools api from Perl, a critical thing I did for speed was allow the specification of the particular columns I was interested in (ie. an Include() instead of an Omit()). Is something like that possible with biogo/hts?

**Comment by kortschak** [comment]
I guess it is conceivable to add that degree of tuning, but I doubt that is where the majority of the cost is.

From memory when I was doing a fair bit of profiling the majority of the cost in actually in the gzip implementation in the standard library (though I may be misremembering), then comes cost from auxiliary tag parsing (hence the Omit method). When I run the benchmarks tomorrow I will instrument the flagstat program and post profiling data here.

**Comment by sb10** [comment]
I haven't looked at how Go's standard library is handling reading of the data, but another important speed improvement in samtools on lustre (the file system I'm using) came about because C stdio queries the filesystem block-size, and increases the read buffers appropriately (to Mb on lustre). Doing small ~kb reads is a big waste.

**Comment by brentp** [comment]
adding buffered IO doesn't change the speed, the limitation is the zlib reader. Here a the CPU profile for flagstat.go:

```
12670ms of 15590ms total (81.27%)
Dropped 115 nodes (cum <= 77.95ms)
Showing top 10 nodes out of 95 (cum >= 170ms)
      flat  flat%   sum%        cum   cum%
    4000ms 25.66% 25.66%    10800ms 69.28%  compress/flate.(*decompressor).huffmanBlock
    2750ms 17.64% 43.30%     5100ms 32.71%  compress/flate.(*decompressor).huffSym
    1990ms 12.76% 56.06%     3160ms 20.27%  compress/flate.(*decompressor).moreBits
    1170ms  7.50% 63.57%     1170ms  7.50%  github.com/biogo/hts/bgzf.(*decompressor).ReadByte
    1140ms  7.31% 70.88%     1140ms  7.31%  runtime.memmove
     620ms  3.98% 74.86%     1500ms  9.62%  runtime.mallocgc
     370ms  2.37% 77.23%      370ms  2.37%  runtime.memclrNoHeapPointers
     270ms  1.73% 78.96%      300ms  1.92%  runtime.scanobject
     190ms  1.22% 80.18%      190ms  1.22%  runtime.heapBitsSetType
     170ms  1.09% 81.27%      170ms  1.09%  syscall.Syscall
```


I use samtools every day and I also didn't know that one could use > 1 thread for flagstat.

**Comment by kortschak** [comment]
There is https://github.com/klauspost/compress. It might be worth looking at the wins and impacts of from using Klaus' gzip package. It is designed to be a drop in replacement, but I think this is not entirely true here exactly because that is the design; `gzip.Header` would not be assignable to the `klauspost/.../gzip.Header` so clients here would have to change their imported gzip to match the package used by bgzf.

**Comment by kortschak** [comment]
If there were a change to Klaus' package there would have to be a header conversion from his Header type to the stdlib when the header is copied out. Whether this would need unsafe conversion is up for investigation.

**Comment by brentp** [comment]
It doesn't look like that's much faster compared to bgzf with 1.7: https://groups.google.com/d/msg/golang-dev/Dn-pfWETUrM/3tR9YRLQAQAJ

hopefully this goes through: https://groups.google.com/forum/#!msg/golang-dev/Dn-pfWETUrM/3tR9YRLQAQAJ

**Comment by kortschak** [comment]
I have rerun the benchmarks and am confident with the numbers I get for the different `GOMAXPROCS` settings. I have also run the multithreaded samtools benches - [PR here](https://github.com/biogo/hts/pull/70).

The profiling code and graph are [here](https://gist.github.com/kortschak/f3dcf73818c81d21b421929f88890d02).

I have tried the experiment of replacing stdlib's `compress/...` with `github.com/klauspost/compress/...` and, disappointingly, see no significant change (if anything it is marginally worse).
