### ISSUE TITLE
Bam reader error on date format

### ISSUE THREAD

**Issue by Defgenx** [biogo/hts#99]
Hello.

I am trying to parse a bam file but I have an error when the lib parse the headers date.
Here is the error : 

> "parsing time "2017-05-10T21:02:29" as "2006-01-02T15:04:05-0700": cannot parse "" as "-0700"

I assume that my sequencer output is not the same as the lib available formats:
`const (
	iso8601Date      = "2006-01-02"
	iso8601TimeDateZ = "2006-01-02T15:04:05Z"
	iso8601TimeDateN = "2006-01-02T15:04:05-0700"
)`

Would you add something that allows to not parse the date if the format is unkown or just reformat it with time.Parse in readGroupLine() from parse_header.go ?

Thanks.

**Comment by kortschak** [comment]
What tool generates that time format? Can you post a failing header except here.

**Comment by Defgenx** [comment]
It is a bam file from (IONTORRENT) Illumina sequencer (I do not know much more about it sorry). It works perfectly with samtools (tested it today). Is it what you wanted to know ?

I can post the header here (if it is a problem I will edit my message later). Here is the header that fails:

> parsing time "2017-05-10T21:02:29" as "2006-01-02T15:04:05-0700": cannot parse "" as "-0700": line 2: "@RG\tID:ZFEE4.IonXpress_001\tCN:TorrentServer/sn12c011810\tDT:2017-05-10T21:02:29\tFO:..."

**Comment by kortschak** [comment]
Fixed by #100.
